inherit_gem:
  google-style: google-style.yml

Metrics/BlockLength:
  Exclude:
    - "serverless.gemspec"
Metrics/ClassLength:
  Exclude:
    - "lib/google/serverless/exec.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/google/serverless/exec.rb""
    - "lib/google/serverless/exec/tasks.rb"
Metrics/ModuleLength:
  Exclude:
    - "lib/google/serverless/exec/tasks.rb"
